### PR TITLE
Add a link to JackTrip.

### PR DESCRIPTION
**Pull request by automaciej**
I haven't seen a mention of JackTrip on the list. When I needed to create a open source based network setup, JackTrip was the most readily available solution. There is a JackTrip application which provides a bridge between network and the JACK daemon. While the current UI and overall use is geared towards playing live with a musician in another location, JackTrip also allows for low latency transfer of multichannel audio over LAN - this was my use. Since I personally tested it out, and it worked well, I think it might deserve a spot on this list. I'm happy to provide more information if needed.

### CODE REVIEW

**Comment by Mo-way** [comment]
Hi, thanks for the link! I never heard of Jacktrip.
You added it in the standards section, however, I can't find a standard document. Is there one?

Alternatively, tools section only consists of AES67 tools, but IMHO other AoIP tools could be there, too

**Comment by automaciej** [comment]
Hm, you're right, there might not be a definitive standard description the same way that exists for AES67. There is a couple papers at https://ccrma.stanford.edu/groups/soundwire/publications/#jacktrip-icmc and there's the implementation. Perhaps thanks to the fact that JackTrip is open source, there was no need for parallel implementations and that's why there might not been explicit description of the standard. Maybe then JackTrip belongs to another section in your list?

**Comment by Mo-way** [comment]
The link to the Github is the commandline tool you get with `sudo apt install jacktrip`, right? If so, could you add it in the `Tools` section, please?

**Comment by automaciej** [comment]
Sure, done!

**Pull request merged**
